# Generated by Django 5.2.14 on 2026-06-13 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('headline', models.CharField(max_length=200)),
                ('bio', models.TextField()),
                ('portfolio_url', models.URLField(blank=True)),
                ('experience_years', models.PositiveSmallIntegerField(default=0)),
                ('motivation', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('review_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='otp',
            new_name='accounts_ot_user_id_563591_idx',
            old_name='accounts_otp_user_3e0f89_idx',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('instructor', 'Instructor')], db_index=True, default='student', max_length=20),
        ),
        migrations.AddField(
            model_name='instructorapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_instructor_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='instructorapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='instructorapplication',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('user',), name='unique_pending_instructor_application_per_user'),
        ),
    ]
