# Generated by Django 6.0.4 on 2026-04-18 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='youtube_url',
            field=models.URLField(blank=True),
        ),
    ]
