# Generated by Django 5.2.12 on 2026-06-02 00:12

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_cartpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=courses.models.Course._thumbnail_upload_to),
        ),
    ]
